version: '3'
services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.app
    ports:
      - "80:80"
    depends_on:
      - db
    networks:
      - blog
  migrations:
    build:
      context: .
      dockerfile: ./Dockerfile.mig
    depends_on:
      - db
    networks:
      - blog
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_DB:       blog
    networks:
      - blog

networks:
  blog:
    driver: bridge